name: Test substring
description: 'test sub-string'

inputs:
  build-path-zip:
    required: true
    type: string
    
runs:
  using: "composite"
  steps:
    - name: Get build path for unzip
      shell: powershell
      run: |
        $buildPath="${{ inputs.build-path-zip }}".Trim().Replace(".zip", "")
        echo "Build path $buildPath"
        if ($buildPath.StartsWith("${{ github.workspace }}", $true, $null)) {
          echo "BUILD_PATH=$buildPath" >> $env:GITHUB_ENV
        }
        else {
          echo "BUILD_PATH=${{ github.workspace }}\$buildPath" >> $env:GITHUB_ENV
        }        
        
    - name: Done
      shell: powershell
      run: echo "Done ${{ env.BUILD_PATH }}"
