name: Test substring
description: 'test sub-string'

inputs:
  build-paths:
    required: true
    type: string
    
runs:
  using: "composite"
  steps:
    - name: Get build path for unzip
      shell: cmd
      run: |
        readarray -t paths <<<"${{ inputs.build-paths }}"
        for each in "${paths[@]}"
        do
          echo "$each"
        done
        
    - name: Done
      shell: cmd
      run: echo "Done"
