name: Test substring
description: 'test sub-string'

inputs:
  build-path:
    required: true
    type: string
    
runs:
  using: "composite"
  steps:
    - name: Get build number
      id: build_number
      shell: pwsh
      run: echo "BUILD_NUMBER=$(date +'%Y.%m.%d').${{ github.run_number }}" >> $env:GITHUB_ENV        
      
    - name: Check condition
      if: ${{ inputs.replace-tokens-files.ToLower().Contains('appsettings') }}
      shell: pwsh
      run: echo "Check condition successfully"
      
    - name: Done
      shell: pwsh
      run: echo "build number ${{ env.BUILD_NUMBER }}"

outputs:
  build-number:
    description: "Build number"
    value: ${{ env.BUILD_NUMBER }}
  build-path-zip:
    description: "Build path zip"
    value: "${{ inputs.build-path }}-${{ env.BUILD_NUMBER }}.zip"
