name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
    
runs:
  using: "composite"
  steps:
    - name: Showlog 1
      if: ${{ inputs.who-to-greet == 'Haha' }}
      run: echo "Hello ${{ inputs.who-to-greet }}."
      shell: bash
    - name: Showlog 111
      if: ${{ inputs.who-to-greet != 'Haha' }}
      run: echo "Hello ${{ inputs.who-to-greet }}."
      shell: bash
    - name: Showlog 2
      id: random-number-generator
      run: echo "set-output name=random-number$(echo $RANDOM)"
      shell: bash
    - name: Set Build Number to environment
      shell: powershell
      run: |
        echo "BUILD_NUMBER=999999999" >> $env:GITHUB_ENV
        echo "BUILD_XXXXXX=999999999" >> $env:GITHUB_ENV
    - name: Showlog 4
      run: |
        echo "Done ${{ env.BUILD_NUMBER }}"
        echo "Done ${{ env.BUILD_XXXXXX }}"
      shell: powershell
